### ISSUE TITLE
Все формы в одном стиле

### ISSUE THREAD

**Issue by arusanov** [getsitecontrol/getsitecontrol-wordpress-plugin#1]
Форму логина сделать как форму сайнап

Вместо:
![image](https://cloud.githubusercontent.com/assets/459176/24235265/7e1ee5aa-0fad-11e7-9d1b-119c506776db.png)

Сделать:
![image](https://cloud.githubusercontent.com/assets/459176/24235306/b53fd03a-0fad-11e7-9684-e39659e4ce9d.png)

Форму выбора сайта тоже сделать в стиле (круглые кнопки)

![image](https://cloud.githubusercontent.com/assets/459176/24235352/f3ece7e6-0fad-11e7-8e06-e10d90727474.png)

Валидация такая же как на сайте

Сейчас:
![image](https://cloud.githubusercontent.com/assets/459176/24235406/368a21c2-0fae-11e7-8458-e9a767ff4e1c.png)

Надо:
![image](https://cloud.githubusercontent.com/assets/459176/24235412/432393b4-0fae-11e7-9291-9fd4fa5ec055.png)

Сообщения валидации не убирать а просто сделать им `display:none` я потом их куда нить приделаю

Желательно вместо своей валидации заюзать что то готовое https://jqueryvalidation.org/

**Comment by arusanov** [comment]
Последняя форма
![image](https://cloud.githubusercontent.com/assets/459176/24247822/50bc112e-0fde-11e7-92de-cf27797d0687.png)

**Comment by Alexey-Umilin** [comment]
Тут вроде надо с дизайнером посоветоваться. Хотя бы расстояния отсмотреть,
размеры.

**Comment by arusanov** [comment]
@Alexey-Umilin все точно такое же как на сайте

**Comment by arusanov** [comment]
Иконка заезжает на текст
![image](https://cloud.githubusercontent.com/assets/459176/24283983/d37a4d24-1079-11e7-9c7f-339c332d6714.png)
