### ISSUE TITLE
Не заполняется email

### ISSUE THREAD

**Issue by arusanov** [getsitecontrol/getsitecontrol-wordpress-plugin#2]
![image](https://cloud.githubusercontent.com/assets/459176/24235540/dfa01eba-0fae-11e7-9dc3-72b5fe90f352.png)

**Comment by arusanov** [comment]
И в сайнин тоже

**Comment by matiosfree** [comment]
Исправлено тут: https://github.com/getsitecontrol/getsitecontrol-wordpress-plugin/commit/c3547e06dfa9f79d305727f45f7bc4d930a44012
