### ISSUE TITLE
Дизейблить форму при отправке запроса

### ISSUE THREAD

**Issue by arusanov** [getsitecontrol/getsitecontrol-wordpress-plugin#3]
Форму при отправке сайнапа/ина надо дизейблить (в идеале как то еще показывать что запрос ушел)

**Comment by matiosfree** [comment]
Исправленно тут: https://github.com/getsitecontrol/getsitecontrol-wordpress-plugin/commit/0f9e9083a43d87bd79c477f0843f26ed0468b538
